FROM python:3.12
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt ./
RUN pip install --upgrade -r requirements.txt

COPY src ./

CMD ["python", "-m", "uvicorn", "main:main", "--host", "0.0.0.0", "--port", "3000", "--workers", "1", "--factory", "--reload"]
